name: My Notes Backend CI/CD

on:
  push:
    paths:
      - "backend/MyNote/MyNote/**"
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Publish app
      - name: Publish app
        run: dotnet publish -c Release -o ./publish

      # Create ZIP package
      - name: Create deployment package
        run: |
          cd publish
          zip -r ../deployment.zip .

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ se crets.AWS_REGION }}

      # Deploy Lambda directly with zip
      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name getMyNote \
            --zip-file fileb://deployment.zip
