name: Frontend CI/CD

on:
  push:
    paths:
      - "frontend/**"
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies (frontend)
      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      # 4. Build Quasar project
      - name: Build project
        run: |
          cd frontend
          npm run build-staging

      # 5. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ se crets.AWS_REGION }}

      # 6. Deploy build output to S3
      - name: Sync to S3
        run: |
          aws s3 sync frontend/dist/spa s3://${{ secrets.AWS_S3_BUCKET }} --delete

      # 7. Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
            --paths "/*"
